# Generated by Django 4.0.3 on 2022-10-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('date2', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='日期')),
                ('view_count', models.IntegerField(verbose_name='访问量')),
            ],
        ),
    ]
